# Generated by Django 4.1.6 on 2023-02-07 02:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("traits", "0002_rename_pets_traits_pet"),
        ("groups", "0002_rename_pets_groups_pet"),
        ("pets", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Pets",
            new_name="Pet",
        ),
    ]
