# Generated by Django 4.1.6 on 2023-02-07 02:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pets", "0002_rename_pets_pet"),
        ("traits", "0002_rename_pets_traits_pet"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Traits",
            new_name="Trait",
        ),
    ]
