# Generated by Django 4.1.6 on 2023-02-07 03:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("traits", "0004_alter_trait_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trait",
            name="pet",
        ),
    ]
