# Generated by Django 4.1.6 on 2023-02-07 02:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pets", "0002_rename_pets_pet"),
        ("groups", "0002_rename_pets_groups_pet"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Groups",
            new_name="Group",
        ),
    ]
